### ISSUE TITLE
Some entrances not working

### ISSUE THREAD

**Issue by Tylerghuygj** [FiendsOfTheElements/FF1Randomizer#267] opened 2019-04-21 15:42 UTC
![Randomized final fantasy-0](https://user-images.githubusercontent.com/49839948/56472282-6fe20c00-642a-11e9-95e5-36b1101b1193.png)

I have random entrances on, and instead of showing an area, (Like Matoya's cave for example) This glitched area that I can't move in with an ogre shows up

**Comment by latzio** [comment] 2019-04-21 15:55
Can you provide the exact flags and seed you used to make this happen? Should be available on the start screen of the game or if you have the URL to the website that's perfect too.

**Comment by Tylerghuygj** [comment] 2019-04-21 15:58
![Randomized final fantasy-1](https://user-images.githubusercontent.com/49839948/56472465-b59fd400-642c-11e9-8e42-332d973b5ca2.png)
This is my title screen. I'm assuming the equipment symbols is the flags?

**Comment by latzio** [comment] 2019-04-21 15:59
Aha thanks. I now suspect the error is caused by your room mods playing funny with FFR. Can you try using the standard USA FF1 Rom with the same seed and flags to see if it still happens?

**Comment by latzio** [comment] 2019-04-21 16:00
Do you have the URL in your browser history to the exact seed and flags you were playing? That's critical to us debugging the issue.

**Comment by Tylerghuygj** [comment] 2019-04-21 16:01
Yeah, I'll try that. It's not too big of a deal since I'm able to reach Chaos in this run, but it'll help for future runs I may decide to do

**Comment by latzio** [comment] 2019-04-21 16:01
The seed is there. The flags will be in the filename or your history.

**Comment by Tylerghuygj** [comment] 2019-04-21 16:05
What is the file name of the standard FF1 rom?

**Comment by Tylerghuygj** [comment] 2019-04-21 16:09
Never mind. I'm pretty sure I figured out the problem

**Comment by latzio** [comment] 2019-04-21 16:10
Thanks. Closing.

**Closed by latzio** 2019-04-21 16:10 UTC
